#!/bin/sh

#  gizmo
#  Copyright 2020 Mark Hubbard, a.k.a. "TheMarkitecht"
#  http://www.TheMarkitecht.com
#
#  Project home:  http://github.com/TheMarkitecht/gizmo
#  gizmo is a GNOME / GTK+ 3 windowing shell for Jim Tcl (http://jim.tcl.tk/)
#  gizmo helps you quickly develop modern cross-platform GUI apps in Tcl.
#
#  This file is part of gizmo.
#
#  gizmo is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  gizmo is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public License
#  along with gizmo.  If not, see <https://www.gnu.org/licenses/>.

set -e

# builder settings
project=`pwd`
optim=0
compile="-pipe -g3 -O$optim -Wall -fPIC -std=c11 -c  \
    -I.  -I../jimsh  -I../dlr/dlrNative-src  -I/usr/include/gobject-introspection-1.0  \
    -DJIM_EMBEDDED  -DBUILD_GIZMO
    `pkg-config --cflags gtk+-3.0`"
link="-pipe -g3 -O$optim -Wall -fPIC -std=c11 -ldl"
linkSO="-pipe -g3 -O$optim -Wall -fPIC -std=c11 -Wl,--export-dynamic  -shared"
gtkLibs=" `pkg-config --libs gtk+-3.0`  -lgirepository-1.0"

set -x

# generate more C source.
../jimsh/jimsh  ../jimsh/make-c-ext.tcl  initgizmo.tcl  > _initgizmo.c

# build gizmo executable.
gcc $compile -o  _initgizmo.o  _initgizmo.c
gcc $compile -o  main.o  main.c
gcc $compile -o  dlrNative-src/dlrNative.o  dlrNative-src/dlrNative.c
gcc $link  -o gizmo  \
    main.o  \
    _initgizmo.o  \
    dlrNative-src/dlrNative.o  \
    /usr/lib/x86_64-linux-gnu/libffi.a  \
    ../jimsh/libjim.a  \
    $gtkLibs

# run automated tests
cd $project
rm -rf ./dlr/dlr-binding/gi/auto  ;# this one forces regeneration of libgirepository wrapper scripts.
rm -rf ./dlr/dlr-binding/g/auto
rm -rf ./dlr/dlr-binding/gio/auto
rm -rf ./dlr/dlr-binding/gdk/auto
rm -rf ./dlr/dlr-binding/gtk/auto
rm -rf ./dlr/dlr-binding/gobject/auto
export JIMLIB=./dlr:./dlrNative-src
./gizmo  test.tcl

# check for memory leak
#todo: valgrind
exit 0
valgrind  -q  --error-exitcode=1  --leak-check=full  --leak-resolution=high  \
    --show-leak-kinds=definite,possible  --errors-for-leak-kinds=definite,possible  \
    ./gizmo  test.tcl    >/dev/null



