#!/bin/sh

#  gizmo
#  Copyright 2020 Mark Hubbard, a.k.a. "TheMarkitecht"
#  http://www.TheMarkitecht.com
#
#  Project home:  http://github.com/TheMarkitecht/gizmo
#  gizmo is a GNOME / GTK+ 3 windowing shell for Jim Tcl (http://jim.tcl.tk/)
#  gizmo helps you quickly develop modern cross-platform GUI apps in Tcl.
#
#  This file is part of gizmo.
#
#  gizmo is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  gizmo is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public License
#  along with gizmo.  If not, see <https://www.gnu.org/licenses/>.

set -e

# builder settings
project=`pwd`
optim=0
compile="-pipe -g3 -O$optim -Wall -fPIC -std=c11 -c  -I.  -I../../jimsh  -I/usr/include/gobject-introspection-1.0  `pkg-config --cflags gtk+-3.0`"
link="-pipe -g3 -O$optim -Wall -fPIC -std=c11 -ldl"
linkSO="-pipe -g3 -O$optim -Wall -fPIC -std=c11 -Wl,--export-dynamic  -shared"
gtkLibs=" `pkg-config --libs gtk+-3.0`  -lgirepository-1.0"

set -x

# build "dlr" extension for Jim.
# include BUILD_GIZMO flag for GI support.
cd ../dlrNative-src
gcc $compile -DBUILD_GIZMO -o dlrNative.o  dlrNative.c
gcc $linkSO -o dlrNative.so  dlrNative.o  /usr/lib/x86_64-linux-gnu/libffi.a  $gtkLibs

# run inspector.
cd $project
export JIMLIB=../dlr:../dlrNative-src
./jimsh  inspector.tcl  refreshMeta  GLib  2.0
./jimsh  inspector.tcl  refreshMeta  Gtk  3.0
